// GENERATED by web/scripts/sync-abi.mjs from out/ClosedAuction.sol/ClosedAuction.json. Do not edit.
export const closedAuctionAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "note_",
        "type": "address"
      },
      {
        "name": "pointer_",
        "type": "address"
      },
      {
        "name": "clock_",
        "type": "address"
      },
      {
        "name": "scorecard_",
        "type": "address"
      },
      {
        "name": "usdg_",
        "type": "address"
      },
      {
        "name": "eligibility_",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "MAX_DECAY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_LIFE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_DECAY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "bid",
    "inputs": [
      {
        "name": "lotId",
        "type": "uint256"
      },
      {
        "name": "maxPrice",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "price",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "clock",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "currentPrice",
    "inputs": [
      {
        "name": "lotId",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "eligibility",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "list",
    "inputs": [
      {
        "name": "noteId",
        "type": "uint256"
      },
      {
        "name": "amount",
        "type": "uint128"
      },
      {
        "name": "startPrice",
        "type": "uint128"
      },
      {
        "name": "floorPrice",
        "type": "uint128"
      },
      {
        "name": "decaySeconds",
        "type": "uint32"
      },
      {
        "name": "endAt",
        "type": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "lotId",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "lotCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "lotOf",
    "inputs": [
      {
        "name": "lotId",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "components": [
          {
            "name": "seller",
            "type": "address"
          },
          {
            "name": "wrapper",
            "type": "address"
          },
          {
            "name": "noteId",
            "type": "uint256"
          },
          {
            "name": "amount",
            "type": "uint128"
          },
          {
            "name": "startPrice",
            "type": "uint128"
          },
          {
            "name": "floorPrice",
            "type": "uint128"
          },
          {
            "name": "refPrice",
            "type": "uint128"
          },
          {
            "name": "startAt",
            "type": "uint64"
          },
          {
            "name": "endAt",
            "type": "uint64"
          },
          {
            "name": "decaySeconds",
            "type": "uint32"
          },
          {
            "name": "epochAtMint",
            "type": "uint32"
          },
          {
            "name": "status",
            "type": "uint8"
          },
          {
            "name": "buyer",
            "type": "address"
          },
          {
            "name": "clearedPrice",
            "type": "uint128"
          },
          {
            "name": "clearedAt",
            "type": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "note",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "onERC1155BatchReceived",
    "inputs": [
      {
        "name": "",
        "type": "address"
      },
      {
        "name": "",
        "type": "address"
      },
      {
        "name": "",
        "type": "uint256[]"
      },
      {
        "name": "",
        "type": "uint256[]"
      },
      {
        "name": "",
        "type": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes4"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "onERC1155Received",
    "inputs": [
      {
        "name": "operator",
        "type": "address"
      },
      {
        "name": "",
        "type": "address"
      },
      {
        "name": "",
        "type": "uint256"
      },
      {
        "name": "",
        "type": "uint256"
      },
      {
        "name": "",
        "type": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes4"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pointer",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "priceAt",
    "inputs": [
      {
        "name": "lotId",
        "type": "uint256"
      },
      {
        "name": "t",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "realisedDiscountBps",
    "inputs": [
      {
        "name": "lotId",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "int256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "scorecard",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "supportsInterface",
    "inputs": [
      {
        "name": "interfaceId",
        "type": "bytes4"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "usdg",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "withdraw",
    "inputs": [
      {
        "name": "lotId",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "Cleared",
    "inputs": [
      {
        "name": "lotId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "noteId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "buyer",
        "type": "address",
        "indexed": true
      },
      {
        "name": "price",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "discountBpsVsRef",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "at",
        "type": "uint64",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Listed",
    "inputs": [
      {
        "name": "lotId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "noteId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "seller",
        "type": "address",
        "indexed": true
      },
      {
        "name": "wrapper",
        "type": "address",
        "indexed": false
      },
      {
        "name": "amount",
        "type": "uint128",
        "indexed": false
      },
      {
        "name": "startPrice",
        "type": "uint128",
        "indexed": false
      },
      {
        "name": "floorPrice",
        "type": "uint128",
        "indexed": false
      },
      {
        "name": "endAt",
        "type": "uint64",
        "indexed": false
      },
      {
        "name": "refPrice",
        "type": "uint128",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Withdrawn",
    "inputs": [
      {
        "name": "lotId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "seller",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "BadParams",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Ineligible",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LotExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LotNotLive",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MarketNotClosed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotPrinted",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotSeller",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotSold",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Overflow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PriceAboveMax",
    "inputs": [
      {
        "name": "price",
        "type": "uint256"
      },
      {
        "name": "max",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "Reentrant",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReopenedSinceMint",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TransferFailed",
    "inputs": [
      {
        "name": "token",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "Unsolicited",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroDenominator",
    "inputs": []
  }
] as const;
