// GENERATED by web/scripts/sync-abi.mjs from out/CurbCredit.sol/CurbCredit.json. Do not edit.
export const curbCreditAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "clock_",
        "type": "address"
      },
      {
        "name": "scorecard_",
        "type": "address"
      },
      {
        "name": "depthCert_",
        "type": "address"
      },
      {
        "name": "eligibility_",
        "type": "address"
      },
      {
        "name": "usdg_",
        "type": "address"
      },
      {
        "name": "admin_",
        "type": "address"
      },
      {
        "name": "assets_",
        "type": "address[]"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "APR_BPS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "CURE_OPEN_SECONDS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "LTV_OPEN_BPS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "LTV_SHUT_BPS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_TICK_GAP",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_CERT_LIFE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "SHUT_CERT_LIFE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "STALE_BONUS_BPS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "acceptAdmin",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "admin",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "assets",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "badDebt",
    "inputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "borrow",
    "inputs": [
      {
        "name": "asset",
        "type": "address"
      },
      {
        "name": "amount",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "clock",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "cureOf",
    "inputs": [
      {
        "name": "borrower",
        "type": "address"
      },
      {
        "name": "asset",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "components": [
          {
            "name": "active",
            "type": "bool"
          },
          {
            "name": "lastOpen",
            "type": "bool"
          },
          {
            "name": "openedAt",
            "type": "uint64"
          },
          {
            "name": "lastTickAt",
            "type": "uint64"
          },
          {
            "name": "openSecondsUsed",
            "type": "uint64"
          },
          {
            "name": "priceAtBreach",
            "type": "uint128"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "debtOf",
    "inputs": [
      {
        "name": "borrower",
        "type": "address"
      },
      {
        "name": "asset",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "defund",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256"
      },
      {
        "name": "to",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "deposit",
    "inputs": [
      {
        "name": "asset",
        "type": "address"
      },
      {
        "name": "shares",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "depthCert",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "eligibility",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "flagBreach",
    "inputs": [
      {
        "name": "borrower",
        "type": "address"
      },
      {
        "name": "asset",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "fund",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "isAsset",
    "inputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isBreached",
    "inputs": [
      {
        "name": "borrower",
        "type": "address"
      },
      {
        "name": "asset",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "known",
        "type": "bool"
      },
      {
        "name": "breached",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isOpen",
    "inputs": [
      {
        "name": "asset",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "limitOf",
    "inputs": [
      {
        "name": "borrower",
        "type": "address"
      },
      {
        "name": "asset",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "liquidate",
    "inputs": [
      {
        "name": "borrower",
        "type": "address"
      },
      {
        "name": "asset",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "ltvFor",
    "inputs": [
      {
        "name": "asset",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "minCertExpiry",
    "inputs": [
      {
        "name": "asset",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingAdmin",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "positionOf",
    "inputs": [
      {
        "name": "borrower",
        "type": "address"
      },
      {
        "name": "asset",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "components": [
          {
            "name": "collateral",
            "type": "uint256"
          },
          {
            "name": "principal",
            "type": "uint256"
          },
          {
            "name": "accrued",
            "type": "uint256"
          },
          {
            "name": "lastAccrual",
            "type": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "realisable",
    "inputs": [
      {
        "name": "asset",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "realise",
    "inputs": [
      {
        "name": "certId",
        "type": "uint256"
      },
      {
        "name": "shares",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "repay",
    "inputs": [
      {
        "name": "borrower",
        "type": "address"
      },
      {
        "name": "asset",
        "type": "address"
      },
      {
        "name": "amount",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "reserve",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "scorecard",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "seized",
    "inputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "sweepSeized",
    "inputs": [
      {
        "name": "asset",
        "type": "address"
      },
      {
        "name": "shares",
        "type": "uint256"
      },
      {
        "name": "to",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "tick",
    "inputs": [
      {
        "name": "borrower",
        "type": "address"
      },
      {
        "name": "asset",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "totalCollateral",
    "inputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "totalPrincipal",
    "inputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "transferAdmin",
    "inputs": [
      {
        "name": "to",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "usdg",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "withdraw",
    "inputs": [
      {
        "name": "asset",
        "type": "address"
      },
      {
        "name": "shares",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "AdminTransferStarted",
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "indexed": true
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AdminTransferred",
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "indexed": true
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Borrowed",
    "inputs": [
      {
        "name": "borrower",
        "type": "address",
        "indexed": true
      },
      {
        "name": "asset",
        "type": "address",
        "indexed": true
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "debtAfter",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "ltvBps",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BreachCured",
    "inputs": [
      {
        "name": "borrower",
        "type": "address",
        "indexed": true
      },
      {
        "name": "asset",
        "type": "address",
        "indexed": true
      },
      {
        "name": "used",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BreachOpened",
    "inputs": [
      {
        "name": "borrower",
        "type": "address",
        "indexed": true
      },
      {
        "name": "asset",
        "type": "address",
        "indexed": true
      },
      {
        "name": "debt",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "limit",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "priceAtBreach",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "ltvBps",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CureTicked",
    "inputs": [
      {
        "name": "borrower",
        "type": "address",
        "indexed": true
      },
      {
        "name": "asset",
        "type": "address",
        "indexed": true
      },
      {
        "name": "open",
        "type": "bool",
        "indexed": false
      },
      {
        "name": "used",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "required",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Defunded",
    "inputs": [
      {
        "name": "to",
        "type": "address",
        "indexed": true
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "reserveAfter",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Deposited",
    "inputs": [
      {
        "name": "borrower",
        "type": "address",
        "indexed": true
      },
      {
        "name": "asset",
        "type": "address",
        "indexed": true
      },
      {
        "name": "shares",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "collateralAfter",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Funded",
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "indexed": true
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "reserveAfter",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Liquidated",
    "inputs": [
      {
        "name": "borrower",
        "type": "address",
        "indexed": true
      },
      {
        "name": "asset",
        "type": "address",
        "indexed": true
      },
      {
        "name": "seized",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "cleared",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "badDebt",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "pFresh",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "pBreach",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Realised",
    "inputs": [
      {
        "name": "certId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "shares",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "filled",
        "type": "bool",
        "indexed": false
      },
      {
        "name": "usdgIn",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Refusal",
    "inputs": [
      {
        "name": "who",
        "type": "address",
        "indexed": true
      },
      {
        "name": "asset",
        "type": "address",
        "indexed": true
      },
      {
        "name": "reason",
        "type": "bytes4",
        "indexed": true
      },
      {
        "name": "requested",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "allowed",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Repaid",
    "inputs": [
      {
        "name": "borrower",
        "type": "address",
        "indexed": true
      },
      {
        "name": "asset",
        "type": "address",
        "indexed": true
      },
      {
        "name": "payer",
        "type": "address",
        "indexed": true
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "debtAfter",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SeizedSwept",
    "inputs": [
      {
        "name": "asset",
        "type": "address",
        "indexed": true
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true
      },
      {
        "name": "shares",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Withdrawn",
    "inputs": [
      {
        "name": "borrower",
        "type": "address",
        "indexed": true
      },
      {
        "name": "asset",
        "type": "address",
        "indexed": true
      },
      {
        "name": "shares",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "collateralAfter",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyInCure",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ApproveFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadDecimals",
    "inputs": [
      {
        "name": "token",
        "type": "address"
      },
      {
        "name": "decimals",
        "type": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "CureIncomplete",
    "inputs": [
      {
        "name": "used",
        "type": "uint256"
      },
      {
        "name": "required",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "DuplicateAsset",
    "inputs": [
      {
        "name": "asset",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ExceedsCollateral",
    "inputs": [
      {
        "name": "collateral",
        "type": "uint256"
      },
      {
        "name": "requested",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ExceedsDepth",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ExceedsLtv",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ExceedsSeized",
    "inputs": [
      {
        "name": "seized",
        "type": "uint256"
      },
      {
        "name": "requested",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InCure",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Ineligible",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MarketShut",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MarketUnknown",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoCode",
    "inputs": [
      {
        "name": "target",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "NoCure",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoDepth",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoPriceSource",
    "inputs": [
      {
        "name": "asset",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotAdmin",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotBreached",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotOurCert",
    "inputs": [
      {
        "name": "certId",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotPendingAdmin",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Overflow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PriceUnavailable",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Reentrancy",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReserveShort",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TransferFailed",
    "inputs": [
      {
        "name": "token",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnsupportedAsset",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WouldBreach",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAmount",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroDenominator",
    "inputs": []
  }
] as const;
