// GENERATED by web/scripts/sync-abi.mjs from out/DepthCert.sol/DepthCert.json. Do not edit.
export const depthCertAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "usdg_",
        "type": "address"
      },
      {
        "name": "makers_",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "ALLOWANCE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes4"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "BALANCE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes4"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "BPS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_LIFE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_LIVE_PER_BOOK",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_LIVE_PER_MAKER",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_BOND_BPS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_GAS_FOR_TRANSFER",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_LIFE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_NOTIONAL",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "TRANSFER_FAILED",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes4"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "TRANSFER_GAS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "bookOf",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      },
      {
        "name": "beneficiary",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "certOf",
    "inputs": [
      {
        "name": "id",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "components": [
          {
            "name": "maker",
            "type": "address"
          },
          {
            "name": "wrapper",
            "type": "address"
          },
          {
            "name": "beneficiary",
            "type": "address"
          },
          {
            "name": "sizeShares",
            "type": "uint128"
          },
          {
            "name": "remainingShares",
            "type": "uint128"
          },
          {
            "name": "bidPx",
            "type": "uint128"
          },
          {
            "name": "bond",
            "type": "uint128"
          },
          {
            "name": "postedAt",
            "type": "uint64"
          },
          {
            "name": "expiry",
            "type": "uint64"
          },
          {
            "name": "status",
            "type": "uint8"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "certsOf",
    "inputs": [
      {
        "name": "maker",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "claimShares",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      },
      {
        "name": "to",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "shares",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "claimableShares",
    "inputs": [
      {
        "name": "",
        "type": "address"
      },
      {
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "committed",
    "inputs": [
      {
        "name": "maker",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "sum",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "honouredDepth",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      },
      {
        "name": "beneficiary",
        "type": "address"
      },
      {
        "name": "minExpiry",
        "type": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "shares",
        "type": "uint256"
      },
      {
        "name": "notional",
        "type": "uint256"
      },
      {
        "name": "minBidPx",
        "type": "uint128"
      },
      {
        "name": "soonestExpiry",
        "type": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isHonourable",
    "inputs": [
      {
        "name": "maker",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "makers",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "nextId",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "post",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      },
      {
        "name": "beneficiary",
        "type": "address"
      },
      {
        "name": "sizeShares",
        "type": "uint128"
      },
      {
        "name": "bidPx",
        "type": "uint128"
      },
      {
        "name": "expiry",
        "type": "uint64"
      },
      {
        "name": "bond",
        "type": "uint128"
      }
    ],
    "outputs": [
      {
        "name": "id",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "prune",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      },
      {
        "name": "beneficiary",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "take",
    "inputs": [
      {
        "name": "id",
        "type": "uint256"
      },
      {
        "name": "shares",
        "type": "uint128"
      },
      {
        "name": "to",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "filled",
        "type": "bool"
      },
      {
        "name": "amount",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "totalBonds",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "usdg",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "withdraw",
    "inputs": [
      {
        "name": "id",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "Faded",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "taker",
        "type": "address",
        "indexed": true
      },
      {
        "name": "maker",
        "type": "address",
        "indexed": true
      },
      {
        "name": "shares",
        "type": "uint128",
        "indexed": false
      },
      {
        "name": "costOwed",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "bondSlashed",
        "type": "uint128",
        "indexed": false
      },
      {
        "name": "reason",
        "type": "bytes4",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Filled",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "taker",
        "type": "address",
        "indexed": true
      },
      {
        "name": "shares",
        "type": "uint128",
        "indexed": false
      },
      {
        "name": "paid",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "remaining",
        "type": "uint128",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Posted",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "maker",
        "type": "address",
        "indexed": true
      },
      {
        "name": "wrapper",
        "type": "address",
        "indexed": true
      },
      {
        "name": "beneficiary",
        "type": "address",
        "indexed": false
      },
      {
        "name": "size",
        "type": "uint128",
        "indexed": false
      },
      {
        "name": "bidPx",
        "type": "uint128",
        "indexed": false
      },
      {
        "name": "bond",
        "type": "uint128",
        "indexed": false
      },
      {
        "name": "expiry",
        "type": "uint64",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SharesClaimed",
    "inputs": [
      {
        "name": "maker",
        "type": "address",
        "indexed": true
      },
      {
        "name": "wrapper",
        "type": "address",
        "indexed": true
      },
      {
        "name": "shares",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Withdrawn",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "maker",
        "type": "address",
        "indexed": true
      },
      {
        "name": "bond",
        "type": "uint128",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "BadExpiry",
    "inputs": [
      {
        "name": "expiry",
        "type": "uint64"
      },
      {
        "name": "earliest",
        "type": "uint64"
      },
      {
        "name": "latest",
        "type": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "BadRecipient",
    "inputs": [
      {
        "name": "to",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "BadShares",
    "inputs": [
      {
        "name": "shares",
        "type": "uint128"
      },
      {
        "name": "remaining",
        "type": "uint128"
      }
    ]
  },
  {
    "type": "error",
    "name": "BadWrapper",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "BelowMinNotional",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BondTooSmall",
    "inputs": [
      {
        "name": "bond",
        "type": "uint256"
      },
      {
        "name": "minBond",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "BookFull",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      },
      {
        "name": "beneficiary",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "CertExpired",
    "inputs": [
      {
        "name": "id",
        "type": "uint256"
      },
      {
        "name": "expiry",
        "type": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "DustRemainder",
    "inputs": [
      {
        "name": "left",
        "type": "uint128"
      }
    ]
  },
  {
    "type": "error",
    "name": "IneligibleMaker",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientGas",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotBeneficiary",
    "inputs": [
      {
        "name": "caller",
        "type": "address"
      },
      {
        "name": "beneficiary",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotLive",
    "inputs": [
      {
        "name": "id",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotMaker",
    "inputs": [
      {
        "name": "caller",
        "type": "address"
      },
      {
        "name": "maker",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotWithdrawable",
    "inputs": [
      {
        "name": "id",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "Overflow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Reentrancy",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TooManyLiveCerts",
    "inputs": [
      {
        "name": "maker",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TransferFailed",
    "inputs": [
      {
        "name": "token",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroCost",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroDenominator",
    "inputs": []
  }
] as const;
