// GENERATED by web/scripts/sync-abi.mjs from out/MarketClock.sol/MarketClock.json. Do not edit.
export const marketClockAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "admin_",
        "type": "address"
      },
      {
        "name": "attestors_",
        "type": "address[]"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "BLACKOUT_WINDOW",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_ATTESTATION_AGE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "acceptAdmin",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "admin",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "assets",
    "inputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "raw",
        "type": "address"
      },
      {
        "name": "mic",
        "type": "bytes4"
      },
      {
        "name": "hoursMode",
        "type": "uint8"
      },
      {
        "name": "registered",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "attest",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      },
      {
        "name": "regime_",
        "type": "uint8"
      },
      {
        "name": "primaryCapUsd",
        "type": "uint128"
      },
      {
        "name": "nextTransitionAt",
        "type": "uint64"
      },
      {
        "name": "halted",
        "type": "bool"
      },
      {
        "name": "inputRoot",
        "type": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "attestBatch",
    "inputs": [
      {
        "name": "wrappers",
        "type": "address[]"
      },
      {
        "name": "regimes",
        "type": "uint8[]"
      },
      {
        "name": "caps",
        "type": "uint128[]"
      },
      {
        "name": "nextAt",
        "type": "uint64[]"
      },
      {
        "name": "halted",
        "type": "bool[]"
      },
      {
        "name": "inputRoot",
        "type": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "blackoutUntil",
    "inputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isAttestor",
    "inputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isInMultiplierBlackout",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingAdmin",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "primaryCapNow",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint128"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "rawToShares",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      },
      {
        "name": "wrapperShares",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "regime",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registerAsset",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      },
      {
        "name": "raw",
        "type": "address"
      },
      {
        "name": "mic",
        "type": "bytes4"
      },
      {
        "name": "hoursMode",
        "type": "uint8"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "registered",
    "inputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registeredCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "secondsToNextTransition",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setAttestor",
    "inputs": [
      {
        "name": "a",
        "type": "address"
      },
      {
        "name": "ok",
        "type": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "stateOf",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "components": [
          {
            "name": "regime",
            "type": "uint8"
          },
          {
            "name": "primaryCapUsd",
            "type": "uint128"
          },
          {
            "name": "nextTransitionAt",
            "type": "uint64"
          },
          {
            "name": "observedAt",
            "type": "uint64"
          },
          {
            "name": "multiplierNonce",
            "type": "uint32"
          },
          {
            "name": "halted",
            "type": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "transferAdmin",
    "inputs": [
      {
        "name": "to",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "AdminTransferStarted",
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "indexed": true
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AdminTransferred",
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "indexed": true
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AssetRegistered",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address",
        "indexed": true
      },
      {
        "name": "raw",
        "type": "address",
        "indexed": true
      },
      {
        "name": "mic",
        "type": "bytes4",
        "indexed": false
      },
      {
        "name": "hoursMode",
        "type": "uint8",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BlackoutOpened",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address",
        "indexed": true
      },
      {
        "name": "fromNonce",
        "type": "uint32",
        "indexed": false
      },
      {
        "name": "toNonce",
        "type": "uint32",
        "indexed": false
      },
      {
        "name": "until",
        "type": "uint64",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RegimeChanged",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address",
        "indexed": true
      },
      {
        "name": "from",
        "type": "uint8",
        "indexed": false
      },
      {
        "name": "to",
        "type": "uint8",
        "indexed": false
      },
      {
        "name": "at",
        "type": "uint64",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "StateAttested",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address",
        "indexed": true
      },
      {
        "name": "regime",
        "type": "uint8",
        "indexed": false
      },
      {
        "name": "primaryCapUsd",
        "type": "uint128",
        "indexed": false
      },
      {
        "name": "nextTransitionAt",
        "type": "uint64",
        "indexed": false
      },
      {
        "name": "multiplierNonce",
        "type": "uint32",
        "indexed": false
      },
      {
        "name": "inputRoot",
        "type": "bytes32",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyRegistered",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "BadQuorum",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotAdmin",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotAttestor",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotPendingAdmin",
    "inputs": []
  },
  {
    "type": "error",
    "name": "StaleAttestation",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      },
      {
        "name": "observedAt",
        "type": "uint64"
      },
      {
        "name": "maxAge",
        "type": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownAsset",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
