// GENERATED by web/scripts/sync-abi.mjs from out/ReopenPointer.sol/ReopenPointer.json. Do not edit.
export const reopenPointerAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "clock_",
        "type": "address"
      },
      {
        "name": "scorecard_",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "PRINT_DELAY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "PRINT_WINDOW",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "clock",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "epochInfo",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      },
      {
        "name": "epoch",
        "type": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "components": [
          {
            "name": "shutSeenAt",
            "type": "uint64"
          },
          {
            "name": "openedAt",
            "type": "uint64"
          },
          {
            "name": "openedBlock",
            "type": "uint64"
          },
          {
            "name": "print",
            "type": "uint128"
          },
          {
            "name": "printedAt",
            "type": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "epochOf",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "headOf",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "components": [
          {
            "name": "epoch",
            "type": "uint32"
          },
          {
            "name": "open",
            "type": "bool"
          },
          {
            "name": "lastShutAt",
            "type": "uint64"
          },
          {
            "name": "lastObservedAt",
            "type": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isOpen",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "observe",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "epoch",
        "type": "uint32"
      },
      {
        "name": "open",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "recordPrint",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      },
      {
        "name": "epoch",
        "type": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "print",
        "type": "uint128"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "scorecard",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "Printed",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address",
        "indexed": true
      },
      {
        "name": "epoch",
        "type": "uint32",
        "indexed": true
      },
      {
        "name": "print",
        "type": "uint128",
        "indexed": false
      },
      {
        "name": "at",
        "type": "uint64",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Reopened",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address",
        "indexed": true
      },
      {
        "name": "epoch",
        "type": "uint32",
        "indexed": true
      },
      {
        "name": "shutSeenAt",
        "type": "uint64",
        "indexed": false
      },
      {
        "name": "openedAt",
        "type": "uint64",
        "indexed": false
      },
      {
        "name": "primaryCapUsd",
        "type": "uint128",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Shut",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address",
        "indexed": true
      },
      {
        "name": "epoch",
        "type": "uint32",
        "indexed": true
      },
      {
        "name": "at",
        "type": "uint64",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyPrinted",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MarketShut",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PrintTooEarly",
    "inputs": [
      {
        "name": "readyAt",
        "type": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "PrintTooLate",
    "inputs": [
      {
        "name": "deadline",
        "type": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "Reentrancy",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownEpoch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
