// GENERATED by web/scripts/sync-abi.mjs from out/ReopenNote.sol/ReopenNote.json. Do not edit.
export const reopenNoteAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "clock_",
        "type": "address"
      },
      {
        "name": "pointer_",
        "type": "address"
      },
      {
        "name": "scorecard_",
        "type": "address"
      },
      {
        "name": "wrappers",
        "type": "address[]"
      },
      {
        "name": "caps",
        "type": "uint256[]"
      },
      {
        "name": "uri_",
        "type": "string"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "FALLBACK_AFTER",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "balanceOf",
    "inputs": [
      {
        "name": "account",
        "type": "address"
      },
      {
        "name": "id",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "balanceOfBatch",
    "inputs": [
      {
        "name": "accounts",
        "type": "address[]"
      },
      {
        "name": "ids",
        "type": "uint256[]"
      }
    ],
    "outputs": [
      {
        "name": "out",
        "type": "uint256[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "cancel",
    "inputs": [
      {
        "name": "id",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "capShares",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "clock",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isApprovedForAll",
    "inputs": [
      {
        "name": "account",
        "type": "address"
      },
      {
        "name": "operator",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "mint",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      },
      {
        "name": "wrapperShares",
        "type": "uint128"
      },
      {
        "name": "to",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "id",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "mintedInEpoch",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      },
      {
        "name": "epoch",
        "type": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "name",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "noteCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "openInterest",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "outstanding",
    "inputs": [
      {
        "name": "id",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint128"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pointer",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "redeem",
    "inputs": [
      {
        "name": "id",
        "type": "uint256"
      },
      {
        "name": "amount",
        "type": "uint128"
      },
      {
        "name": "to",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "redeemable",
    "inputs": [
      {
        "name": "id",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "safeBatchTransferFrom",
    "inputs": [
      {
        "name": "from",
        "type": "address"
      },
      {
        "name": "to",
        "type": "address"
      },
      {
        "name": "ids",
        "type": "uint256[]"
      },
      {
        "name": "values",
        "type": "uint256[]"
      },
      {
        "name": "data",
        "type": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "safeTransferFrom",
    "inputs": [
      {
        "name": "from",
        "type": "address"
      },
      {
        "name": "to",
        "type": "address"
      },
      {
        "name": "id",
        "type": "uint256"
      },
      {
        "name": "value",
        "type": "uint256"
      },
      {
        "name": "data",
        "type": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "scorecard",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setApprovalForAll",
    "inputs": [
      {
        "name": "operator",
        "type": "address"
      },
      {
        "name": "approved",
        "type": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "supportedAssets",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "supportsInterface",
    "inputs": [
      {
        "name": "interfaceId",
        "type": "bytes4"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "symbol",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "unitOf",
    "inputs": [
      {
        "name": "id",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "components": [
          {
            "name": "wrapper",
            "type": "address"
          },
          {
            "name": "issuer",
            "type": "address"
          },
          {
            "name": "wrapperShares",
            "type": "uint128"
          },
          {
            "name": "underlyingAtMint",
            "type": "uint128"
          },
          {
            "name": "multiplierNonce",
            "type": "uint32"
          },
          {
            "name": "epochAtMint",
            "type": "uint32"
          },
          {
            "name": "mintedAt",
            "type": "uint64"
          },
          {
            "name": "mintedBlock",
            "type": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "uri",
    "inputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "ApprovalForAll",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "indexed": true
      },
      {
        "name": "operator",
        "type": "address",
        "indexed": true
      },
      {
        "name": "approved",
        "type": "bool",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "NoteCancelled",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "issuer",
        "type": "address",
        "indexed": true
      },
      {
        "name": "wrapperShares",
        "type": "uint128",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "NoteMinted",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "issuer",
        "type": "address",
        "indexed": true
      },
      {
        "name": "wrapper",
        "type": "address",
        "indexed": true
      },
      {
        "name": "wrapperShares",
        "type": "uint128",
        "indexed": false
      },
      {
        "name": "underlyingAtMint",
        "type": "uint128",
        "indexed": false
      },
      {
        "name": "multiplierNonce",
        "type": "uint32",
        "indexed": false
      },
      {
        "name": "epochAtMint",
        "type": "uint32",
        "indexed": false
      },
      {
        "name": "to",
        "type": "address",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "NoteRedeemed",
    "inputs": [
      {
        "name": "id",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "holder",
        "type": "address",
        "indexed": true
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true
      },
      {
        "name": "wrapperShares",
        "type": "uint128",
        "indexed": false
      },
      {
        "name": "underlyingAtRedeem",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "nonceAtRedeem",
        "type": "uint32",
        "indexed": false
      },
      {
        "name": "epochNow",
        "type": "uint32",
        "indexed": false
      },
      {
        "name": "viaFallback",
        "type": "bool",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TransferBatch",
    "inputs": [
      {
        "name": "operator",
        "type": "address",
        "indexed": true
      },
      {
        "name": "from",
        "type": "address",
        "indexed": true
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true
      },
      {
        "name": "ids",
        "type": "uint256[]",
        "indexed": false
      },
      {
        "name": "values",
        "type": "uint256[]",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TransferSingle",
    "inputs": [
      {
        "name": "operator",
        "type": "address",
        "indexed": true
      },
      {
        "name": "from",
        "type": "address",
        "indexed": true
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true
      },
      {
        "name": "id",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "value",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "BadConfig",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CapExceeded",
    "inputs": [
      {
        "name": "oi",
        "type": "uint256"
      },
      {
        "name": "cap",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC1155InsufficientBalance",
    "inputs": [
      {
        "name": "from",
        "type": "address"
      },
      {
        "name": "id",
        "type": "uint256"
      },
      {
        "name": "balance",
        "type": "uint256"
      },
      {
        "name": "needed",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC1155LengthMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ERC1155NotAuthorized",
    "inputs": [
      {
        "name": "operator",
        "type": "address"
      },
      {
        "name": "from",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC1155UnsafeRecipient",
    "inputs": [
      {
        "name": "to",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ERC1155ZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EscrowMismatch",
    "inputs": [
      {
        "name": "received",
        "type": "uint256"
      },
      {
        "name": "expected",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InBlackout",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidRecipient",
    "inputs": [
      {
        "name": "to",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "MarketNotClosed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoPriceSource",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotReopened",
    "inputs": [
      {
        "name": "id",
        "type": "uint256"
      },
      {
        "name": "epochAtMint",
        "type": "uint32"
      },
      {
        "name": "epochNow",
        "type": "uint32"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotWholeIssuer",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Reentrancy",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TransferFailed",
    "inputs": [
      {
        "name": "token",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownNote",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnsupportedAsset",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ValueOverflow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAmount",
    "inputs": []
  }
] as const;
