// GENERATED by web/scripts/sync-abi.mjs from out/Scorecard.sol/Scorecard.json. Do not edit.
export const scorecardAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "clock_",
        "type": "address"
      },
      {
        "name": "admin_",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "MAX_TICK_DEVIATION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "int24"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_OBSERVATION_CARDINALITY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "SETTLE_DELAY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "SETTLE_WINDOW",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "acceptAdmin",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "admin",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "clock",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "closureCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "closureIds",
    "inputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "commit",
    "inputs": [
      {
        "name": "c",
        "type": "tuple",
        "components": [
          {
            "name": "wrapper",
            "type": "address"
          },
          {
            "name": "committedAt",
            "type": "uint64"
          },
          {
            "name": "committedBlock",
            "type": "uint64"
          },
          {
            "name": "settleAfter",
            "type": "uint64"
          },
          {
            "name": "mark",
            "type": "uint128"
          },
          {
            "name": "bandBps",
            "type": "uint32"
          },
          {
            "name": "inputRoot",
            "type": "bytes32"
          },
          {
            "name": "methodDigest",
            "type": "bytes32"
          },
          {
            "name": "lastPrint",
            "type": "uint128"
          },
          {
            "name": "closingVwap",
            "type": "uint128"
          },
          {
            "name": "staleOracle",
            "type": "uint128"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "id",
        "type": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "commitments",
    "inputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "wrapper",
        "type": "address"
      },
      {
        "name": "committedAt",
        "type": "uint64"
      },
      {
        "name": "committedBlock",
        "type": "uint64"
      },
      {
        "name": "settleAfter",
        "type": "uint64"
      },
      {
        "name": "mark",
        "type": "uint128"
      },
      {
        "name": "bandBps",
        "type": "uint32"
      },
      {
        "name": "inputRoot",
        "type": "bytes32"
      },
      {
        "name": "methodDigest",
        "type": "bytes32"
      },
      {
        "name": "lastPrint",
        "type": "uint128"
      },
      {
        "name": "closingVwap",
        "type": "uint128"
      },
      {
        "name": "staleOracle",
        "type": "uint128"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "curbBeatClosingVwap",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "curbBeatLastPrint",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isKeeper",
    "inputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingAdmin",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "priceNow",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint128"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "priceSources",
    "inputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "pool",
        "type": "address"
      },
      {
        "name": "equityIsToken0",
        "type": "bool"
      },
      {
        "name": "twapWindow",
        "type": "uint32"
      },
      {
        "name": "equityDecimals",
        "type": "uint8"
      },
      {
        "name": "stableDecimals",
        "type": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setKeeper",
    "inputs": [
      {
        "name": "k",
        "type": "address"
      },
      {
        "name": "ok",
        "type": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setPriceSource",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      },
      {
        "name": "pool",
        "type": "address"
      },
      {
        "name": "equityIsToken0",
        "type": "bool"
      },
      {
        "name": "twapWindow",
        "type": "uint32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "settle",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "settledCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "settlements",
    "inputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "settledAt",
        "type": "uint64"
      },
      {
        "name": "settledBlock",
        "type": "uint64"
      },
      {
        "name": "reopenPrint",
        "type": "uint128"
      },
      {
        "name": "curbErrorBps",
        "type": "uint32"
      },
      {
        "name": "lastPrintErrorBps",
        "type": "uint32"
      },
      {
        "name": "closingVwapErrorBps",
        "type": "uint32"
      },
      {
        "name": "staleOracleErrorBps",
        "type": "uint32"
      },
      {
        "name": "source",
        "type": "uint8"
      },
      {
        "name": "settled",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "skill",
    "inputs": [],
    "outputs": [
      {
        "name": "settled_",
        "type": "uint256"
      },
      {
        "name": "beatLast",
        "type": "uint256"
      },
      {
        "name": "beatVwap",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "transferAdmin",
    "inputs": [
      {
        "name": "to",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "AdminTransferStarted",
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "indexed": true
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AdminTransferred",
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "indexed": true
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ClosureCommitted",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "wrapper",
        "type": "address",
        "indexed": true
      },
      {
        "name": "mark",
        "type": "uint128",
        "indexed": false
      },
      {
        "name": "bandBps",
        "type": "uint32",
        "indexed": false
      },
      {
        "name": "settleAfter",
        "type": "uint64",
        "indexed": false
      },
      {
        "name": "committedBlock",
        "type": "uint64",
        "indexed": false
      },
      {
        "name": "inputRoot",
        "type": "bytes32",
        "indexed": false
      },
      {
        "name": "methodDigest",
        "type": "bytes32",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ClosureSettled",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "wrapper",
        "type": "address",
        "indexed": true
      },
      {
        "name": "reopenPrint",
        "type": "uint128",
        "indexed": false
      },
      {
        "name": "curbErrorBps",
        "type": "uint32",
        "indexed": false
      },
      {
        "name": "lastPrintErrorBps",
        "type": "uint32",
        "indexed": false
      },
      {
        "name": "closingVwapErrorBps",
        "type": "uint32",
        "indexed": false
      },
      {
        "name": "staleOracleErrorBps",
        "type": "uint32",
        "indexed": false
      },
      {
        "name": "source",
        "type": "uint8",
        "indexed": false
      },
      {
        "name": "settledBlock",
        "type": "uint64",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PriceSourceSet",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address",
        "indexed": true
      },
      {
        "name": "pool",
        "type": "address",
        "indexed": true
      },
      {
        "name": "equityIsToken0",
        "type": "bool",
        "indexed": false
      },
      {
        "name": "twapWindow",
        "type": "uint32",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadySettled",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "BadMark",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadTwapWindow",
    "inputs": [
      {
        "name": "twapWindow",
        "type": "uint32"
      }
    ]
  },
  {
    "type": "error",
    "name": "ClosureExists",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "MarketStillOpen",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "MarketStillShut",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "NoPriceSource",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotAdmin",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotKeeper",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotPendingAdmin",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OracleTooShallow",
    "inputs": [
      {
        "name": "pool",
        "type": "address"
      },
      {
        "name": "cardinality",
        "type": "uint16"
      }
    ]
  },
  {
    "type": "error",
    "name": "Overflow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PoolEmpty",
    "inputs": [
      {
        "name": "pool",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "PoolMismatch",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      },
      {
        "name": "pool",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "PriceDeviates",
    "inputs": [
      {
        "name": "spotTick",
        "type": "int24"
      },
      {
        "name": "twapTick",
        "type": "int24"
      }
    ]
  },
  {
    "type": "error",
    "name": "PriceSourceLocked",
    "inputs": [
      {
        "name": "wrapper",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "PriceUnreadable",
    "inputs": [
      {
        "name": "pool",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TooEarly",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32"
      },
      {
        "name": "readyAt",
        "type": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "TooLate",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32"
      },
      {
        "name": "deadline",
        "type": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownClosure",
    "inputs": [
      {
        "name": "id",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroDenominator",
    "inputs": []
  }
] as const;
