// Generated by web/og/brand/build.mjs from geometry.mjs — do not edit by hand.
// The mark in a 243.4×243.4 box centred on (121.7, 121.7), R = 100; the 16 px glyph variant in a 16×16 box.
export const MARK_BOX = 243.4;
export const MARK_CENTRE = 121.7;
/** Degrees from due east to each end of the C (the gap is twice this). */
export const C_HALF_GAP = 62;
export const MARK_C = 'M178.83 14.25A121.7 121.7 0 1 0 178.83 229.15L158.46 190.83A78.3 78.3 0 1 1 158.46 52.57Z';
export const MARK_ARC = 'M197.8 200.5A109.55 109.55 0 0 0 197.8 42.9L184.53 56.64A90.45 90.45 0 0 1 184.53 186.76Z';
/** The C split at due west: upper half and lower half (for the "confirmed" motion, each rotates to close). */
export const MARK_C_UPPER = 'M178.83 14.25A121.7 121.7 0 0 0 0 121.7L43.4 121.7A78.3 78.3 0 0 1 158.46 52.57Z';
export const MARK_C_LOWER = 'M0 121.7A121.7 121.7 0 0 0 178.83 229.15L158.46 190.83A78.3 78.3 0 0 1 43.4 121.7Z';
export const MARK_RING = 'M243.4 121.7A121.7 121.7 0 1 0 0 121.7A121.7 121.7 0 1 0 243.4 121.7ZM200 121.7A78.3 78.3 0 1 1 43.4 121.7A78.3 78.3 0 1 1 200 121.7Z';
export const GLYPH_C = 'M11.05 2.26A6.5 6.5 0 1 0 11.05 13.74L10.11 11.97A4.5 4.5 0 1 1 10.11 4.03Z';
export const GLYPH_ARC = 'M12.98 12.18A6.5 6.5 0 0 0 12.98 3.82L11.83 4.79A5 5 0 0 1 11.83 11.21Z';
export const GLYPH_RING = 'M14.5 8A6.5 6.5 0 1 0 1.5 8A6.5 6.5 0 1 0 14.5 8ZM12.5 8A4.5 4.5 0 1 1 3.5 8A4.5 4.5 0 1 1 12.5 8Z';
export const GLYPH_DOTS = 'M7 2.5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0ZM3.11 4.11a1 1 0 1 0 2 0a1 1 0 1 0 -2 0ZM1.5 8a1 1 0 1 0 2 0a1 1 0 1 0 -2 0ZM3.11 11.89a1 1 0 1 0 2 0a1 1 0 1 0 -2 0ZM7 13.5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0ZM10.89 11.89a1 1 0 1 0 2 0a1 1 0 1 0 -2 0ZM12.5 8a1 1 0 1 0 2 0a1 1 0 1 0 -2 0ZM10.89 4.11a1 1 0 1 0 2 0a1 1 0 1 0 -2 0Z';
