// Generated by web/og/brand/build.mjs from geometry.mjs — do not edit by hand.
// The mark in a 242×242 box centred on (121, 121), R = 100; the 16 px glyph variant in a 16×16 box.
export const MARK_BOX = 242;
export const MARK_CENTRE = 121;
/** Degrees from due east to each end of the C (the gap is twice this). */
export const C_HALF_GAP = 62;
export const MARK_C = 'M177.81 14.16A121 121 0 1 0 177.81 227.84L158.09 190.75A79 79 0 1 1 158.09 51.25Z';
export const MARK_ARC = 'M197.41 200.13A110 110 0 0 0 197.41 41.87L183.52 56.26A90 90 0 0 1 183.52 185.74Z';
/** The C split at due west: upper half and lower half (for the "confirmed" motion, each rotates to close). */
export const MARK_C_UPPER = 'M177.81 14.16A121 121 0 0 0 0 121L42 121A79 79 0 0 1 158.09 51.25Z';
export const MARK_C_LOWER = 'M0 121A121 121 0 0 0 177.81 227.84L158.09 190.75A79 79 0 0 1 42 121Z';
export const MARK_RING = 'M242 121A121 121 0 1 0 0 121A121 121 0 1 0 242 121ZM200 121A79 79 0 1 1 42 121A79 79 0 1 1 200 121Z';
export const GLYPH_C = 'M11.05 2.26A6.5 6.5 0 1 0 11.05 13.74L10.11 11.97A4.5 4.5 0 1 1 10.11 4.03Z';
export const GLYPH_ARC = 'M12.98 12.18A6.5 6.5 0 0 0 12.98 3.82L11.83 4.79A5 5 0 0 1 11.83 11.21Z';
export const GLYPH_RING = 'M14.5 8A6.5 6.5 0 1 0 1.5 8A6.5 6.5 0 1 0 14.5 8ZM12.5 8A4.5 4.5 0 1 1 3.5 8A4.5 4.5 0 1 1 12.5 8Z';
export const GLYPH_DOTS = 'M7 2.5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0ZM3.11 4.11a1 1 0 1 0 2 0a1 1 0 1 0 -2 0ZM1.5 8a1 1 0 1 0 2 0a1 1 0 1 0 -2 0ZM3.11 11.89a1 1 0 1 0 2 0a1 1 0 1 0 -2 0ZM7 13.5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0ZM10.89 11.89a1 1 0 1 0 2 0a1 1 0 1 0 -2 0ZM12.5 8a1 1 0 1 0 2 0a1 1 0 1 0 -2 0ZM10.89 4.11a1 1 0 1 0 2 0a1 1 0 1 0 -2 0Z';
