#!/usr/bin/env node
/**
 * Regenerate web/src/data/abi/*.ts from forge's out/ directory.
 *
 *   forge build                        # at the repo root
 *   node web/scripts/sync-abi.mjs      # or: node web/scripts/sync-abi.mjs --out path/to/out
 *   node web/scripts/sync-abi.mjs --check   # exit 1 if any generated file would change
 *
 * Each contract in TARGETS is written as `export const <name>Abi = [...] as const;` with internalType
 * stripped (viem ignores it). Contracts not yet in out/ keep their hand-written file (written from
 * docs/specs/W3W4-contracts.md) and are reported, so the lead can see which ABIs are still provisional.
 * After syncing, grep the readers for "GUESS" and reconcile any getter the real contract names differently.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
const outFlag = args.indexOf("--out");
const OUT = resolve(outFlag >= 0 ? args[outFlag + 1] : join(here, "../../out"));
const CHECK = args.includes("--check");
const ABI_DIR = join(here, "../src/data/abi");

/** contract name in out/ → [file stem in abi/, export name] */
const TARGETS = {
  MarketClock: ["marketClock", "marketClockAbi"],
  Scorecard: ["scorecard", "scorecardAbi"],
  ReopenPointer: ["reopenPointer", "reopenPointerAbi"],
  ReopenNote: ["reopenNote", "reopenNoteAbi"],
  ClosedAuction: ["closedAuction", "closedAuctionAbi"],
  EligibilityRegistry: ["eligibility", "eligibilityAbi"],
  DepthCert: ["depthCert", "depthCertAbi"],
  CurbCredit: ["curbCredit", "curbCreditAbi"],
};

function strip(node) {
  if (Array.isArray(node)) return node.map(strip);
  if (node && typeof node === "object") {
    const o = {};
    for (const [k, v] of Object.entries(node)) {
      if (k === "internalType") continue;
      o[k] = strip(v);
    }
    return o;
  }
  return node;
}

let changed = 0;
let missing = [];
for (const [contract, [stem, exportName]] of Object.entries(TARGETS)) {
  const artifact = join(OUT, `${contract}.sol`, `${contract}.json`);
  if (!existsSync(artifact)) {
    missing.push(contract);
    continue;
  }
  const { abi } = JSON.parse(readFileSync(artifact, "utf8"));
  const body =
    `// GENERATED by web/scripts/sync-abi.mjs from out/${contract}.sol/${contract}.json. Do not edit.\n` +
    `export const ${exportName} = ${JSON.stringify(strip(abi), null, 2)} as const;\n`;
  const target = join(ABI_DIR, `${stem}.ts`);
  const before = existsSync(target) ? readFileSync(target, "utf8") : "";
  if (before !== body) {
    changed++;
    if (CHECK) console.log(`would update abi/${stem}.ts from ${contract}`);
    else {
      writeFileSync(target, body);
      console.log(`abi/${stem}.ts  <- out/${contract}.sol (${abi.length} entries)`);
    }
  } else {
    console.log(`abi/${stem}.ts  unchanged`);
  }
}
if (missing.length) console.log(`not in ${OUT} (hand-written ABI kept, provisional): ${missing.join(", ")}`);
if (CHECK && changed) process.exit(1);
