// Generated by capture/term-build.mjs from terminal/*.json (+ terminal/live/*.json). Do not edit.
window.CURB_TERM = {
 "HZ": {
  "id": "HZ",
  "title": "curl",
  "show": "curl -s https://attestor-a-production.up.railway.app/healthz",
  "startedAt": "2026-09-25T03:55:16.223Z",
  "endedAt": "2026-09-25T03:55:17.806Z",
  "exitCode": 0,
  "output": "{\"ok\":true,\"lastTickOkMs\":1790308514092,\"isAttestor\":true,\"mode\":\"live\",\"address\":\"0x842e9eeE514C419183Ca79D4cb0dc30ad29fEeC4\",\"attribution\":{\"on\":true,\"dataSuffix\":\"0x6464377535306e636b74356537323966100080218021802180218021802180218021\",\"codes\":[\"dd7u50nckt5e729f\"]},\"balanceWei\":\"67944341366753284\",\"lastRound\":{\"root\":\"0x4750913db81b87e313235499d36744a5c3c2604f6c132d2a41fc3b89fd1398b7\",\"kind\":\"diff\",\"tx\":\"0x5d0ca4ad51e277f4630feb3989e930afce2bf83d2e04af917928be5bf13ee1ff\",\"atMs\":1790308504461},\"archive\":{\"enabled\":true,\"bucket\":\"curb-archive\",\"queued\":0,\"parked\":0,\"published\":85,\"alreadyPresent\":0,\"failed\":0,\"lastPublished\":{\"key\":\"rounds/0x4750913db81b87e313235499d36744a5c3c2604f6c132d2a41fc3b89fd1398b7.json\",\"atMs\":1790308504854},\"lastError\":null}}",
  "chunks": [
   [
    1578,
    761
   ]
  ],
  "source": "terminal/live/HZ.json"
 },
 "T1": {
  "id": "T1",
  "title": "cast",
  "show": "cast call 0x160Dc415902971a7a9B5ade7f43005b36FE5B09b \"stateOf(address)((uint8,uint128,uint64,uint64,uint32,bool))\" 0x41333Df9E7639188BBfca5522dC4844398Af9f9E --rpc-url https://rpc.xlayer.tech",
  "startedAt": "2026-09-25T03:55:17.810Z",
  "endedAt": "2026-09-25T03:55:22.606Z",
  "exitCode": 0,
  "output": "(1, 0, 1790308800 [1.79e9], 1790308506 [1.79e9], 0, false)\n",
  "chunks": [
   [
    4791,
    59
   ]
  ],
  "source": "terminal/live/T1.json"
 },
 "T2": {
  "id": "T2",
  "title": "curl",
  "show": "curl -si \"https://api.curb.markets/v1/closure-calendar?symbol=wTCENTx\"",
  "startedAt": "2026-09-24T13:55:32.324Z",
  "endedAt": "2026-09-24T13:55:33.934Z",
  "exitCode": 0,
  "output": "HTTP/2 402 \r\naccess-control-allow-headers: PAYMENT-SIGNATURE, X-PAYMENT, Content-Type, Accept\r\naccess-control-allow-methods: GET, POST, OPTIONS\r\naccess-control-allow-origin: *\r\naccess-control-expose-headers: PAYMENT-REQUIRED, PAYMENT-RESPONSE, x-curb-receipt\r\ncache-control: no-store\r\ncontent-type: application/json\r\ndate: Thu, 24 Sep 2026 13:55:33 GMT\r\npayment-required: eyJ4NDAyVmVyc2lvbiI6MiwiZXJyb3IiOiJQYXltZW50IHJlcXVpcmVkIiwicmVzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly9hcGkuY3VyYi5tYXJrZXRzL3YxL2Nsb3N1cmUtY2FsZW5kYXIiLCJkZXNjcmlwdGlvbiI6IkNsb3N1cmUgY2FsZW5kYXIgZm9yIG9uZSB0b2tlbml6ZWQgZXF1aXR5IG9uIFggTGF5ZXIgKGRlZmF1bHQgd1RDRU5UeCk6IGV2ZXJ5IHdpbmRvdyBpbiB0aGUgbmV4dCAxLTE0IGRheXMgKGRlZmF1bHQgNykgaW4gd2hpY2ggdGhlIGlzc3VlcidzIHByaW1hcnkgb3JkZXIgY2FwIGlzIHplcm8sIGFuZCB0aGUgaW5zdGFudCBpdCByZXR1cm5zLCBjb21wdXRlZCBmcm9tIHRoZSBpc3N1ZXIncyBwdWJsaXNoZWQgc2NoZWR1bGUgYW5kIGxpbWl0cyBwbHVzIGl0cyBvYnNlcnZlZCBjdXQgdG8gemVybyA1IG1pbnV0ZXMgYmVmb3JlIGVhY2ggcGVyaW9kIGVuZHMuIEluY2x1ZGVzIHRoZSBjdXJyZW50IHBlcmlvZCBhbmQgY2FwLCBhbmQgdGhlIGhhc2hlcyBvZiB0aGUgZXhhY3QgaXNzdWVyIHJlc3BvbnNlcyB1c2VkLiIsIm1pbWVUeXBlIjoiYXBwbGljYXRpb24vanNvbiJ9LCJhY2NlcHRzIjpbeyJzY2hlbWUiOiJleGFjdCIsIm5ldHdvcmsiOiJlaXAxNTU6MTk2IiwiYW1vdW50IjoiMTAwMDAiLCJhc3NldCI6IjB4Nzc5ZGVkMGM5ZTEwMjIyMjVmOGUwNjMwYjM1YTliNTRiZTcxMzczNiIsInBheVRvIjoiMHgyNzdjQTkxMjc2QTM4MDE2NjdCNzZDOTdEYTM4NzJDY2I2RTk2MDY4IiwibWF4VGltZW91dFNlY29uZHMiOjMwMCwiZXh0cmEiOnsibmFtZSI6IlVTROKCrjAiLCJ2ZXJzaW9uIjoiMSJ9fV19\r\nserver: railway-hikari\r\nx-railway-request-id: Rx4PqsfAS_ekEkPqmrpb1w\r\ncontent-length: 281\r\nx-hikari-trace: sin1.98a6\r\nx-railway-edge: sin1\r\nvary: accept-encoding\r\n\r\n{\"schema\":\"curb.asp.calendar.preview/1\",\"symbol\":\"wTCENTx\",\"mic\":\"XHKG\",\"marketOpen\":false,\"nowPeriod\":\"closed\",\"nextClosure\":{\"startMs\":1790308500000,\"endMs\":1790312400000,\"durationS\":3900,\"startIso\":\"2026-09-25T03:55:00.000Z\",\"endIso\":\"2026-09-25T05:00:00.000Z\",\"kind\":\"recess\"}}",
  "chunks": [
   [
    1608,
    1892
   ]
  ],
  "source": "terminal/T2.json"
 },
 "T3q": {
  "id": "T3q",
  "title": "onchainos",
  "show": "onchainos payment quote \"https://api.curb.markets/v1/closure-calendar?symbol=wTCENTx\"",
  "startedAt": "2026-09-24T13:55:33.935Z",
  "endedAt": "2026-09-24T13:55:39.236Z",
  "exitCode": 0,
  "output": "{\"ok\":true,\"data\":{\"accepts\":[{\"amount\":\"10000\",\"asset\":\"0x779ded0c9e1022225f8e0630b35a9b54be713736\",\"index\":0,\"network\":\"eip155:196\",\"scheme\":\"exact\"}],\"alternatives\":[],\"candidates\":[{\"acceptsIndex\":0,\"amount\":\"10000\",\"amountHuman\":\"0.01\",\"availableAmount\":\"1.051866\",\"balanceStatus\":\"sufficient\",\"chainId\":\"196\",\"chainName\":\"X Layer\",\"decimals\":6,\"depositAddress\":\"0x055ba8acd60a2287b2d01cb3bf237e4424357105\",\"hasBalance\":true,\"isMainnet\":true,\"recommended\":true,\"requiredAmount\":\"0.01\",\"scheme\":\"exact\",\"shortfall\":\"0\",\"tokenSymbol\":\"USDT\"}],\"decodedChallenge\":{\"amount\":\"10000\",\"amountHuman\":\"0.01\",\"decimals\":6,\"expires\":0,\"recipient\":\"0x277cA91276A3801667B76C97Da3872Ccb6E96068\",\"supported\":true,\"unsupported_reason\":null},\"knownParams\":{},\"merchantBody\":\"{\\\"schema\\\":\\\"curb.asp.calendar.preview/1\\\",\\\"symbol\\\":\\\"wTCENTx\\\",\\\"mic\\\":\\\"XHKG\\\",\\\"marketOpen\\\":false,\\\"nowPeriod\\\":\\\"closed\\\",\\\"nextClosure\\\":{\\\"startMs\\\":1790308500000,\\\"endMs\\\":1790312400000,\\\"durationS\\\":3900,\\\"startIso\\\":\\\"2026-09-25T03:55:00.000Z\\\",\\\"endIso\\\":\\\"2026-09-25T05:00:00.000Z\\\",\\\"kind\\\":\\\"recess\\\"}}\",\"missingParams\":[],\"needsConfirm\":true,\"nextStep\":\"onchainos payment pay --payment-id pay_648de30316555c1fa23efc6a --selected-index <n> --yes\",\"paramPlan\":[],\"paymentId\":\"pay_648de30316555c1fa23efc6a\",\"summary\":\"Will pay 0.01 USDT (exact, X Layer)\"}}\n",
  "chunks": [
   [
    5298,
    1335
   ]
  ],
  "source": "terminal/T3q.json"
 },
 "T3r": {
  "id": "T3r",
  "title": "curl",
  "show": "curl -s https://api.curb.markets/receipts/0xcee1ee75f7323746b96afa5f4056640507a96d02316ba40f9010ac2d58a9817c.json",
  "startedAt": "2026-09-24T13:55:39.237Z",
  "endedAt": "2026-09-24T13:55:40.925Z",
  "exitCode": 0,
  "output": "{\"schema\":\"curb.asp.receipt/1\",\"receiptId\":\"0xcee1ee75f7323746b96afa5f4056640507a96d02316ba40f9010ac2d58a9817c\",\"route\":\"GET /v1/closure-calendar\",\"query\":{\"symbol\":\"wTCENTx\",\"horizonDays\":7},\"network\":\"eip155:196\",\"scheme\":\"exact\",\"asset\":\"0x779ded0c9e1022225f8e0630b35a9b54be713736\",\"amount\":\"10000\",\"payTo\":\"0x277cA91276A3801667B76C97Da3872Ccb6E96068\",\"payer\":\"0x055ba8acd60a2287b2d01cb3bf237e4424357105\",\"transaction\":\"0xe8740458e49025873da915705e05c8a1156882813e81411caea1d2f8ce1b4de7\",\"settleStatus\":\"success\",\"requirementsDigest\":\"0x46882186f9f946ed650b7984bba0ed44aaa916b18cf1cec2befa16fc52a3c674\",\"payloadDigest\":\"0xf962d3224a1b53929c10bfa9e222e9bf31f04ee60bc97f4696b7d29ef9f16353\",\"responseDigest\":\"0x902e20a0bba4a98fc9a5e5bea60d3d7c35fffa8a9e3f141f6915c61c450dec4f\",\"responseBytes\":2256,\"contentType\":\"application/json; charset=utf-8\",\"tsMs\":1790250980602}",
  "chunks": [
   [
    1687,
    867
   ]
  ],
  "source": "terminal/T3r.json"
 },
 "T4": {
  "id": "T4",
  "title": "curb-verify",
  "show": "node tools/curb-verify/src/cli.ts bundle https://attestor-a-production.up.railway.app/rounds/0x4750913db81b87e313235499d36744a5c3c2604f6c132d2a41fc3b89fd1398b7.json",
  "startedAt": "2026-09-25T03:55:25.180Z",
  "endedAt": "2026-09-25T03:55:27.882Z",
  "exitCode": 0,
  "output": "round bundle 0x4750913db81b87e313235499d36744a5c3c2604f6c132d2a41fc3b89fd1398b7\n  source     https://attestor-a-production.up.railway.app/rounds/0x4750913db81b87e313235499d36744a5c3c2604f6c132d2a41fc3b89fd1398b7.json\n  root       0x4750913db81b87e313235499d36744a5c3c2604f6c132d2a41fc3b89fd1398b7\n  kind       diff\n  evaluated  2026-09-25T03:55:04Z\n  claims     6\n  REPRODUCED\n",
  "chunks": [
   [
    2690,
    377
   ]
  ],
  "source": "terminal/live/T4.json"
 },
 "T4s": {
  "id": "T4s",
  "title": "curb-verify",
  "show": "node tools/curb-verify/src/cli.ts selftest",
  "startedAt": "2026-09-24T14:05:48.652Z",
  "endedAt": "2026-09-24T14:05:48.881Z",
  "exitCode": 0,
  "output": "  ok    round-70617365  claims re-derive: root 0xe48cde50188a98adf457f121f308c89f29176b92ccc56728f2e0647f992956b5\n  ok    round-70617365  wrong label is surfaced, not hidden: top-level kind=\"diff\" contradicts committed PARAMS.kind=\"heartbeat\"\n  ok    round-70617365  catches tampering: rejected: JSON preimage hash mismatch for 0x578e23b8a7070b57071e2bc7e1ad62d999a1d47d6e780df5fc9bc8d3ffc90beb\n  ok    round-70619137  claims re-derive: root 0xaa249f49efe5b3ee9834db512039f74ad299fa0146fc174cf6518cb4a8dd6978\n  ok    round-70619137  labels agree with the root: every top-level field matches its committed counterpart\n  ok    round-70619137  catches tampering: rejected: JSON preimage hash mismatch for 0x8dc8b5365356ca98f2be3e80a9bb2cf8dd0cfc1038e4381364411848be5b8691\nselftest passed: 6 checks over 2 real mainnet rounds, no network\n",
  "chunks": [
   [
    226,
    114
   ],
   [
    226,
    720
   ]
  ],
  "source": "terminal/T4s.json"
 },
 "T5": {
  "id": "T5",
  "title": "node",
  "show": "node decode-8021.mjs 0x5d0ca4ad51e277f4630feb3989e930afce2bf83d2e04af917928be5bf13ee1ff",
  "startedAt": "2026-09-25T03:55:22.608Z",
  "endedAt": "2026-09-25T03:55:25.179Z",
  "exitCode": 0,
  "output": "tx        0x5d0ca4ad51e277f4630feb3989e930afce2bf83d2e04af917928be5bf13ee1ff\nblock     71,539,470  status 1\nfrom      0x842e9eee514c419183ca79d4cb0dc30ad29feec4\nto        0x160dc415902971a7a9b5ade7f43005b36fe5b09b\nselector  0xe42c6251\ncalldata  1,350 bytes; the last 34 are the attribution suffix\ntail      …6464377535306e636b74356537323966100080218021802180218021802180218021\n\n  codes   6464377535306e636b74356537323966   \"dd7u50nckt5e729f\"\n  length  10                                 16 bytes\n  schema  00                                 schema 0\n  marker  80218021802180218021802180218021   ERC-8021\n\nox        Attribution.fromData → {\"codes\":[\"dd7u50nckt5e729f\"],\"id\":0}\nresult    Builder Code dd7u50nckt5e729f attached\n",
  "chunks": [
   [
    2519,
    77
   ],
   [
    2566,
    31
   ],
   [
    2566,
    127
   ],
   [
    2566,
    62
   ],
   [
    2566,
    80
   ],
   [
    2566,
    1
   ],
   [
    2566,
    64
   ],
   [
    2566,
    54
   ],
   [
    2566,
    229
   ]
  ],
  "source": "terminal/live/T5.json"
 },
 "T6": {
  "id": "T6",
  "title": "curl",
  "show": "curl -s \"https://api.curb.markets/v1/relay/binance/klines?symbol=HK0700USDT&startTime=1790251200000&limit=1\"",
  "startedAt": "2026-09-24T14:24:22.106Z",
  "endedAt": "2026-09-24T14:24:24.785Z",
  "exitCode": 0,
  "output": "[[1790251200000,\"438.58000\",\"438.59000\",\"438.58000\",\"438.59000\",\"0.39\",1790251259999,\"171.0482000\",3,\"0.39\",\"171.0482000\",\"0\"]]",
  "chunks": [
   [
    2677,
    127
   ]
  ],
  "source": "terminal/T6.json"
 },
 "T4m": {
  "id": "T4m",
  "title": "curb-verify",
  "show": "node tools/curb-verify/src/cli.ts bundle 0xafa10cb0fb2c3b88889378f5a87d3da1ec4ab7f8b2bd40708ea391ce1c77f1a5 --archive https://archive.curb.markets",
  "startedAt": "2026-09-25T04:54:17.955Z",
  "endedAt": "2026-09-25T04:54:21.210Z",
  "exitCode": 0,
  "output": "mark bundle 0xafa10cb0fb2c3b88889378f5a87d3da1ec4ab7f8b2bd40708ea391ce1c77f1a5\n  source     https://archive.curb.markets/marks/0xafa10cb0fb2c3b88889378f5a87d3da1ec4ab7f8b2bd40708ea391ce1c77f1a5.json\n  root       0xafa10cb0fb2c3b88889378f5a87d3da1ec4ab7f8b2bd40708ea391ce1c77f1a5\n  scorecard  0x3b4076c364AbDaE93e6419CeAdEEe8CB283BEf1f\n  evaluated  2026-09-25T04:50:27Z\n  marks      1\n  REPRODUCED\n",
  "chunks": [
   [
    3251,
    397
   ]
  ],
  "source": "terminal/live/T4m.json"
 }
};
