// Compile saved terminal records into terminal/outputs.js, the data file index.html reads.
//
// Sources, later wins: terminal/<ID>.json (captured any time) then terminal/live/<ID>.json (the Fri 25 Sep
// live window). So a live capture replaces the rehearsal automatically, and nothing is hand-edited.
// The output is verbatim: `output` is byte-for-byte what the command printed. `chunks` keep the arrival
// times so the film types the output at the pace it really arrived (compressed to fit the shot).

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const VIDEO_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const DIRS = [path.join(VIDEO_DIR, "terminal"), path.join(VIDEO_DIR, "terminal", "live")];

const recs = {};
for (const dir of DIRS) {
  if (!fs.existsSync(dir)) continue;
  for (const f of fs.readdirSync(dir).sort()) {
    if (!f.endsWith(".json")) continue;
    const r = JSON.parse(fs.readFileSync(path.join(dir, f), "utf8"));
    if (r.schema !== "curb.video.terminal/1") continue;
    recs[r.id] = {
      id: r.id, title: r.title, show: r.show, startedAt: r.startedAt, endedAt: r.endedAt,
      exitCode: r.exitCode, output: r.output,
      chunks: r.chunks.map((c) => [c.t, c.s.length]),
      source: path.relative(VIDEO_DIR, path.join(dir, f)),
    };
  }
}
const out = path.join(VIDEO_DIR, "terminal", "outputs.js");
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out,
  "// Generated by capture/term-build.mjs from terminal/*.json (+ terminal/live/*.json). Do not edit.\n" +
  "window.CURB_TERM = " + JSON.stringify(recs, null, 1) + ";\n");
console.log(`terminal/outputs.js: ${Object.keys(recs).sort().map((k) => `${k}@${recs[k].startedAt.slice(11, 19)}Z`).join(" ")}`);
