// Write the home page's static markup (src/pages/home/markup.ts) into web/index.html inside <main id="main">, so
// the hero H1 and the ring poster paint from HTML (LCP) and page.ts only hydrates. Idempotent: the block sits
// between <!--hm:start--> and <!--hm:end--> markers. Usage (from web/lab/ring): node scripts/home-markup.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createServer } from 'vite';

const web = join(dirname(fileURLToPath(import.meta.url)), '../../..');
const server = await createServer({ root: web, configFile: false, logLevel: 'error', server: { middlewareMode: true }, appType: 'custom' });
try {
  const { homeMarkup } = await server.ssrLoadModule('/src/pages/home/markup.ts');
  const { slotsFromOpen } = await server.ssrLoadModule('/src/ring/layout.ts');
  const { weekSlots } = await server.ssrLoadModule('/src/data/schedule.ts');
  const w = weekSlots(Date.now());
  const html = homeMarkup({ slots: slotsFromOpen(w.open), nowIndex: w.nowIndex, regime: 'shut' });

  const file = join(web, 'index.html');
  const src = readFileSync(file, 'utf8');
  const block = `<!--hm:start (generated by web/lab/ring/scripts/home-markup.mjs from src/pages/home/markup.ts)-->\n${html}\n      <!--hm:end-->`;
  const out = /<!--hm:start[\s\S]*?<!--hm:end-->/.test(src)
    ? src.replace(/<!--hm:start[\s\S]*?<!--hm:end-->/, block)
    : src.replace(/(<main id="main"[^>]*>)[\s\S]*?(<\/main>)/, `$1\n      ${block}\n    $2`);
  if (out === src) console.log('index.html unchanged');
  else {
    writeFileSync(file, out);
    console.log(`wrote ${file} (${html.length} chars of markup)`);
  }
} finally {
  await server.close();
}
